version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains Airbnb listings
    columns:

      - name: listing_id
        description: primary key for the listing
        tests:
          - unique
          - not_null

      - name: host_id
        description: host's id.  references host table
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        description: type of room / apart
        tests:
          - accepted_values:
              values: ['Entire home/apt','Private room', 'Shared room', 'Hotel room']

      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
        tests:
          - positive_value

  - name: dim_hosts_cleansed
    columns:
      
      - name: host_id
        tests:
          - not_null
          - unique
 
      - name: host_name
        tests:
          - not_null
      
      - name: is_superhost
        tests:
          - accepted_values:
              values: ['t', 'f']
          - not_null
 
  - name: fct_reviews_cleansed
    columns:
 
      - name: listing_id
        tests:
          - relationships:
              to: ref('dim_listings_cleansed')
              field: listing_id
 
      - name: reviewer_name
        tests:
          - not_null

      - name: review_sentiment
        tests:
          - accepted_values:
              values: ['positive', 'neutral', 'negative']